# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serialSetting.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SerialDialog(object):
    def setupUi(self, SerialDialog):
        SerialDialog.setObjectName("SerialDialog")
        SerialDialog.resize(261, 343)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Picture/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SerialDialog.setWindowIcon(icon)
        self.SerialSettingGroupBox = QtWidgets.QGroupBox(SerialDialog)
        self.SerialSettingGroupBox.setGeometry(QtCore.QRect(10, 10, 241, 261))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.SerialSettingGroupBox.setFont(font)
        self.SerialSettingGroupBox.setObjectName("SerialSettingGroupBox")
        self.layoutWidget = QtWidgets.QWidget(self.SerialSettingGroupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 86, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.layoutWidget1 = QtWidgets.QWidget(self.SerialSettingGroupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(100, 20, 131, 231))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.PortBox = QtWidgets.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        self.PortBox.setFont(font)
        self.PortBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.PortBox.setCurrentText("")
        self.PortBox.setObjectName("PortBox")
        self.verticalLayout_3.addWidget(self.PortBox)
        self.BaudarteBox = QtWidgets.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        self.BaudarteBox.setFont(font)
        self.BaudarteBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.BaudarteBox.setCurrentText("")
        self.BaudarteBox.setObjectName("BaudarteBox")
        self.verticalLayout_3.addWidget(self.BaudarteBox)
        self.DataBitsBox = QtWidgets.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        self.DataBitsBox.setFont(font)
        self.DataBitsBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.DataBitsBox.setObjectName("DataBitsBox")
        self.verticalLayout_3.addWidget(self.DataBitsBox)
        self.ParityBox = QtWidgets.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        self.ParityBox.setFont(font)
        self.ParityBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ParityBox.setObjectName("ParityBox")
        self.verticalLayout_3.addWidget(self.ParityBox)
        self.StopBitsBox = QtWidgets.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        self.StopBitsBox.setFont(font)
        self.StopBitsBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.StopBitsBox.setObjectName("StopBitsBox")
        self.verticalLayout_3.addWidget(self.StopBitsBox)
        self.FlowTypeBox = QtWidgets.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        self.FlowTypeBox.setFont(font)
        self.FlowTypeBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.FlowTypeBox.setObjectName("FlowTypeBox")
        self.verticalLayout_3.addWidget(self.FlowTypeBox)
        self.RefreshPortButton = QtWidgets.QPushButton(SerialDialog)
        self.RefreshPortButton.setGeometry(QtCore.QRect(136, 281, 118, 28))
        self.RefreshPortButton.setMinimumSize(QtCore.QSize(118, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.RefreshPortButton.setFont(font)
        self.RefreshPortButton.setObjectName("RefreshPortButton")
        self.OpenPortButton = QtWidgets.QPushButton(SerialDialog)
        self.OpenPortButton.setEnabled(True)
        self.OpenPortButton.setGeometry(QtCore.QRect(11, 281, 118, 28))
        self.OpenPortButton.setMinimumSize(QtCore.QSize(118, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.OpenPortButton.setFont(font)
        self.OpenPortButton.setObjectName("OpenPortButton")
        self.TipLabel = QtWidgets.QLabel(SerialDialog)
        self.TipLabel.setGeometry(QtCore.QRect(10, 320, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.TipLabel.setFont(font)
        self.TipLabel.setObjectName("TipLabel")
        self.line = QtWidgets.QFrame(SerialDialog)
        self.line.setGeometry(QtCore.QRect(0, 310, 261, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(SerialDialog)
        QtCore.QMetaObject.connectSlotsByName(SerialDialog)

    def retranslateUi(self, SerialDialog):
        _translate = QtCore.QCoreApplication.translate
        SerialDialog.setWindowTitle(_translate("SerialDialog", "Serial Port"))
        self.SerialSettingGroupBox.setTitle(_translate("SerialDialog", "Port settings"))
        self.label_9.setText(_translate("SerialDialog", "Port"))
        self.label_8.setText(_translate("SerialDialog", "Baudarte"))
        self.label_11.setText(_translate("SerialDialog", "Data Bits"))
        self.label_12.setText(_translate("SerialDialog", "Parity"))
        self.label_13.setText(_translate("SerialDialog", "Stop Bits"))
        self.label_14.setText(_translate("SerialDialog", "Flow Type"))
        self.RefreshPortButton.setText(_translate("SerialDialog", "Refresh Port"))
        self.OpenPortButton.setText(_translate("SerialDialog", "Open Port"))
        self.TipLabel.setText(_translate("SerialDialog", "TextLabel"))

