# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(711, 645)
        MainWindow.setMinimumSize(QtCore.QSize(0, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Picture/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(40, 40))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 16, 691, 591))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tipsLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tipsLabel.setFont(font)
        self.tipsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tipsLabel.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard)
        self.tipsLabel.setObjectName("tipsLabel")
        self.gridLayout_5.addWidget(self.tipsLabel, 6, 0, 1, 1)
        self.titleLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout_5.addWidget(self.titleLabel, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.UpdateLogText = QtWidgets.QTextBrowser(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.UpdateLogText.setFont(font)
        self.UpdateLogText.setObjectName("UpdateLogText")
        self.gridLayout_2.addWidget(self.UpdateLogText, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 7, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.filePathEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.filePathEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.filePathEdit.setFont(font)
        self.filePathEdit.setObjectName("filePathEdit")
        self.gridLayout_4.addWidget(self.filePathEdit, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.BrowseButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.BrowseButton.setFont(font)
        self.BrowseButton.setObjectName("BrowseButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.BrowseButton)
        self.UpdateButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.UpdateButton.setFont(font)
        self.UpdateButton.setObjectName("UpdateButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.UpdateButton)
        self.gridLayout_4.addLayout(self.formLayout, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 4, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.processLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.processLabel.setFont(font)
        self.processLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.processLabel.setObjectName("processLabel")
        self.gridLayout_3.addWidget(self.processLabel, 0, 0, 1, 1)
        self.UpdateBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.UpdateBar.setProperty("value", 32)
        self.UpdateBar.setTextVisible(False)
        self.UpdateBar.setObjectName("UpdateBar")
        self.gridLayout_3.addWidget(self.UpdateBar, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.myMenuBar = QtWidgets.QMenuBar(MainWindow)
        self.myMenuBar.setGeometry(QtCore.QRect(0, 0, 711, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.myMenuBar.setFont(font)
        self.myMenuBar.setObjectName("myMenuBar")
        self.menuSerial_Port = QtWidgets.QMenu(self.myMenuBar)
        self.menuSerial_Port.setObjectName("menuSerial_Port")
        self.menuHelp = QtWidgets.QMenu(self.myMenuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.myMenuBar)
        self.actionSetting = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Picture/Setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSetting.setIcon(icon1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.actionSetting.setFont(font)
        self.actionSetting.setObjectName("actionSetting")
        self.help = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Picture/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help.setIcon(icon2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.help.setFont(font)
        self.help.setObjectName("help")
        self.menuSerial_Port.addSeparator()
        self.menuSerial_Port.addAction(self.actionSetting)
        self.menuHelp.addAction(self.help)
        self.myMenuBar.addAction(self.menuSerial_Port.menuAction())
        self.myMenuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Handset Firmware Updater"))
        self.tipsLabel.setText(_translate("MainWindow", "Please wait while the update process is going…"))
        self.titleLabel.setText(_translate("MainWindow", "Firmware Update"))
        self.label_7.setText(_translate("MainWindow", "Upgrade firmware log"))
        self.UpdateLogText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"><br /></p></body></html>"))
        self.filePathEdit.setText(_translate("MainWindow", "No File Selected"))
        self.BrowseButton.setText(_translate("MainWindow", "Browse"))
        self.UpdateButton.setText(_translate("MainWindow", "Upgrade"))
        self.label_4.setText(_translate("MainWindow", "Select the file location"))
        self.label.setText(_translate("MainWindow", "Click the Browse button to select the upgrade file from hard disk"))
        self.label_5.setText(_translate("MainWindow", "Upgrade the firmware"))
        self.label_6.setText(_translate("MainWindow", "Click the Upgrade button to complete the firmware upgrade process"))
        self.processLabel.setText(_translate("MainWindow", "32 % completed"))
        self.menuSerial_Port.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSetting.setText(_translate("MainWindow", "Serial Port"))
        self.actionSetting.setIconText(_translate("MainWindow", "Serial Port"))
        self.help.setText(_translate("MainWindow", "Hi bro, what do you want?"))

